### ISSUE TITLE
Please add the following <18 check at wakeup

### ISSUE THREAD

**Issue by fahd-arshad** [covid-alert-ny/covid-green-app#483]
We will need to add an under 18 gate at the beginning of the onboarding flow. 

Please see attached mocks for layout and copy. @helloantoine and @ahurworth will need to discuss some VX and layout details, so please don't commit to that while they work those out, but the general flow will be as mocked up by Alex in this image:

![image](https://user-images.githubusercontent.com/68031284/93732623-fbfbe400-fb86-11ea-9673-a3cf08183577.png)

The OK button on the 3rd screen will bring you back to the first screen. 

Below is an alternate, but **not the one currently being requested**. I am attaching it here in case we get asked to do this one-screen approach on Mon NY time; however, ATM we conservatively would plan for the longer 3-screen approach above, in the hope of meeting our intended code-freeze. 
 
<img width="301" alt="COVID app age gate option 3f" src="https://user-images.githubusercontent.com/68031284/93732741-7b89b300-fb87-11ea-91f2-daefead1afe3.png">

**Comment by AlanSl** [comment]
@ahurworth @fahd-arshad Can you please confirm that this text, taken from the first three screenshots, is confirmed as what we need translating and is all we need translating for this issue (for example, that we shouldn't get translations for the 1-screen version because there is no chance of a late switch to that version?):

```
{
  "ageRequirement": {
    "notice": "Are you over 18?",
    "over": "Yes",
    "under": "No"
  },
  "underAge": {
    "notice": "Did your parent or guardian confirm you can use this app?",
    "yes": "Yes",
    "no": "No",
    "unconfirmed": "Sorry… You cannot use this app without parent or guardian confirmation.",
    "okay": "OK"
  }
}
```

**Comment by ahurworth** [comment]
Looks good to me.

**Comment by helloantoine** [comment]
@AlanSl @floridemai @JohnAGill Here's the confirmed design (currently):
![new onboarding](https://user-images.githubusercontent.com/16833643/93859265-51ceaa00-fcb5-11ea-9111-0bfaa216cab1.png)

**Overview**
One single screen added before the introduction screen. This means we're expecting more translations.

**Todo**
- [x] a. Create new screen: https://zpl.io/aw8Jgyd
- [x] b. QA with Large Font setting
- [x] c. QA with ScreenReader
- [x] d. QA with TalkBack
- [x] e. Add functionality to go Back (header link) in the Introduction screen
- [x] e. Update the link in the Delete my data. Once it's done it should link back to the age gate, NOT the introduction.


**Assets:**
[logo-AlertNY18.svg.zip](https://github.com/project-vagabond/covid-green-app/files/5260008/logo-AlertNY18.svg.zip)

**Comment by fahd-arshad** [comment]
Here is the language from NYS: 
I am over 18, or I am the parent or guardian of a minor confirming that they can use the app.

**Comment by floridemai** [comment]
@helloantoine Should be available in the next build

**Comment by kevin-sheldon** [comment]
This has been verified. However, need to open up a new ticket to fix language in next release. 

It should read "I am at least 18 years of age" instead of "I am over 18". People may think you may need to be 19 or older to use this app, and 18 is the minimum age.

**Comment by AlanSl** [comment]
@kevin-sheldon Sure, in that case do you want to close this issue, open that as a new issue for the next update, and when the translations are ready post them to that new issue and assign me to it?
